### ISSUE TITLE
Version solving (PubGrub)

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-test-rs#10]
PubGrub is a version solving algorithm, written in 2018 by Natlie Weizenbaum for the Dart package manager. It is supposed to be very fast and to explain errors more clearly than the alternatives. An introductory blog post was [published on Medium](https://medium.com/@nex3/pubgrub-2fb6470504f) by it author.

The detailed explanation of the algorithm is [provided on GitHub](https://github.com/dart-lang/pub/blob/master/doc/solver.md). The foundation of the algorithm is based on ASP (Answer Set Programming) and a book called "[Answer Set Solving in Practice](https://potassco.org/book/)" by Martin Gebser, Roland Kaminski, Benjamin Kaufmann and Torsten Schaub.

Currently, this work is done by the elm-json binary. Eventually, it would be useful to extract the dependency solving algorithm from elm-json into a crate of its own. This would also allow using it offline with already installed packages. The solver code in elm-json has been extracted from [elba](https://github.com/elba/elba), a package manager for the Idris language. It seems to be a Rust implementation of PubGrub, but not in a very suitable form for a library ([tightly bound to to elba's semantics and CLI context](https://github.com/elba/elba/issues/44)).

**Comment by harrysarson** [comment]
Exciting! I would be very interested to know what advantages elba got from tightly binding the solver to the sematics and CLI. Does it, for example, make the error messages nicer? Or is it tighly bound simply because creating a nice API boundary requires effort that the folk at elba prefered to invest in something else.

I have read about, but do not understand, a project within the rust compiler to "library-ify the source code" [1][]. The idea being that they have all this tightly bound code and they want to split it into separate libraries. I thought that maybe it could provide inspiration to us. The language in the pubgrub blog post reminded me of how this article talks about queries -- maybe there is some useful overlap here (from the point of view of encapsulating API's rather than version solving).

[1]: http://smallcultfollowing.com/babysteps/blog/2020/04/09/libraryification/

**Comment by mpizenberg** [comment]
Summary of the medium article:

## terminology

* term : range of versions either required or forbidden (menu >= 1.1.0, not dropdown >= 2.0.0, etc.)
* incompatibilities : set of terms that may not all be satisfied at once.

The trick is figuring out how to generate incompatibilities that are both true and likely to be useful.
Deriving incompatibilities is called "clause learning" in the approach known as "conflict-driven clause learning".

## Core loop

PubGrub alternates between two phases:
1. unit propagation
2. decision making

### Unit propagation

Combines the list of selected package versions with incompatibilities. Terms satisfied by the selected package versions and present in multi-terms incompatibilities are used to derive new terms that must be satisfied. Once there are no more derivations to make PubGrub moves to phase 2, decision making.

### Decision making

For packages that are not chosen yet, use a heuristic (recent, old, fewest versions, ...) and add them to the list of package versions. Also add new incompatibilities derived from that package dependencies.

### Conflict resolution

If unit propagation derives a term making an incompatibility fully satisfied, we go into conflict resolution. We record the root cause of terms violation in a new incompatibility that will avoid doing the same mistake later.

The root cause is iteratively computed through a logical rule of derivation known as "resolution" (P|Q & R|-Q => P|R). With incompatibilities it means that {S,T} and {U, not T} implies {S, U}. For this, we need to recall the chain of unit propagation.

Keeping the chain of conflict resolutions also helps in delivering great error messages such as:

> Because dropdown >=2.0.0 depends on icons >=2.0.0 and root depends on icons <2.0.0, **dropdown >=2.0.0 is forbidden**.
>
> And because menu >=1.1.0 depends on dropdown >=2.0.0, **menu >=1.1.0 is forbidden**.
>
> And because menu <1.1.0 depends on dropdown >=1.0.0 <2.0.0 which depends on intl <4.0.0, **every version of menu requires intl <4.0.0**.
>
> So, because root depends on both menu >=1.0.0 and intl >=5.0.0, **version solving failed**.

Generally, it isn't necessarily a straight line, but a DAG (directed acyclic graph). PubGrub uses depth-first traversal plus other tricks to produce the error message.

**Comment by mpizenberg** [comment]
> Exciting! I would be very interested to know what advantages elba got from tightly binding the solver to the sematics and CLI. Does it, for example, make the error messages nicer? Or is it tighly bound simply because creating a nice API boundary requires effort that the folk at elba prefered to invest in something else.

I think this was mostly because it was easier to do it with a practical case, and to invest time on other things, but I wouldn't speak for them.

> I have read about (but do not really understand too much about) a project within the rust compiler to "library-ify the source code" [1](http://smallcultfollowing.com/babysteps/blog/2020/04/09/libraryification/).

I think this is also related to trying to use the same code base for rust-analyzer (which is weirdly not mentioned in that post). This is probably a too big project to be useful to us in my opinion but if there are lessons to be learned, they are welcomed :)

**Comment by mpizenberg** [comment]
Version solving via pugrub has now been merged. The code is visible in the new `deps` module.
