### ISSUE TITLE
Compatibility with lamdera

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-test-rs#104]
[Lamdera](https://lamdera.com/) is an alternative compiler for full stack elm projects.

Since it adds a set of packages that do not exist in the official elm repositories, such as `lamdera/core` and `lamdera/codecs`, elm-test-rs currently cannot run in online mode. This is because the online mode builds the index of existing packages exclusively by talking to the package server.

However, if all dependencies are already downloaded on your computer, `elm-test-rs --offline` should work to run your tests in a lamdera project.

So currently, the requirements to be able to run elm-test-rs in a lamdera project are:

1. Having at least once called `lamdera make` in your lamdera project
2. Having at least once called `elm-test-rs` in a normal elm project
3. Call `elm-test-rs --offline` in your lamdera project to make sure its used in offline mode

A solution to this awkward situation would be to have an online mode that combines what exists on the packages server and what exists in your `~/.elm/` directory instead of exclusively the package server.

**Comment by dillonkearns** [comment]
Thanks for writing up these details! A small workflow tip in case anyone finds it useful: if you add a test script like this in your package.json

```json
{
  "scripts": {
    "test": "elm-test-rs --offline",
    "postinstall": "elm-tooling install"
  },
  "devDependencies": {
    "elm-tooling": "^1.6.0"
  }
}
```

Then you can run `npm test` or `npm test -- --watch` (or add arbitrary flags to the base with --offline after the `npm test -- ...`).
