### ISSUE TITLE
Generated package.json in main_helper is not valid json

### ISSUE THREAD

**Issue by jjant** [mpizenberg/elm-test-rs#106]
This line https://github.com/mpizenberg/elm-test-rs/blob/ddf5ffe4b75e819f00ccaef3ba05afb47aa772ef/src/run.rs#L172 generates a file that looks like:
```json
{ type: 'commonjs' }
```

This is not valid json, strings use `"` instead of `'` and keys **have** to be quoted:
```json
{ "type": "commonjs" }
```

**Comment by mpizenberg** [comment]
woops, sorry good catch! Don't hesitate to make the PR if you want. Otherwise I can do it a bit later

**Comment by jjant** [comment]
@mpizenberg Done! Thanks for the quick reply.
