### ISSUE TITLE
Avoid need for elmi-to-json on path

### ISSUE THREAD

**Issue by harrysarson** [mpizenberg/elm-test-rs#11]
Currently, we require an elmi-to-json executable to be installed. We would like elm-test-rs to be a stand alone executable and so we need to find an alternative. I see two:

1. Use Haskell c ffi bindings: http://wiki.haskell.org/FFI_complete_examples#When_main_is_in_C.2B.2B

2. Go for my way of finding tests. Rough idea goes something like: https://gist.github.com/harrysarson/08acee2e8d8ffb0185b4b1020c08d756

3. write a .elmi parser in Rust ^^.

I like 2. more but I haven't succiently written down what 2. involves let alone implemeneted it so 1. may be a better short term solution.

**Comment by mpizenberg** [comment]
A third option is to write a .elmi parser in Rust ^^.
I will be occupied with colors, pretty printing and pubgrub for quite some time so I'll let you investigate these 2 (3?) options if that's ok.

**Comment by harrysarson** [comment]
I have spent some time trying to get the elmi-to-json code compiled into a static library. Is a really pain and I think would be a quite big burden to maintain even if I did get it working.

Maybe I need to look into 2. or 3. and see if they are feasible.

**Comment by mpizenberg** [comment]
Annoying indeed! In short, what are the main difficulties you encountered?

**Comment by harrysarson** [comment]
Current progress for dropping elmi-to-json altogether https://github.com/rtfeldman/node-test-runner/pull/442

**Comment by mpizenberg** [comment]
Merged #15
