### ISSUE TITLE
Add to crates.io

### ISSUE THREAD

**Issue by sevensidedmarble** [mpizenberg/elm-test-rs#116]
I didn't see this on crates.io, any chance it could be added?

**Comment by mpizenberg** [comment]
There is a possibility indeed. Nobody asked for it yet and I assumed the Elm community prefers a precompiled binary so I didn't pack it on crates.

Is it just a question out of curiosity or does publishing on crates has a real added value for you?

**Comment by mpizenberg** [comment]
Considering elm-test-rs is a binary crate, I suppose you wanted this to be able to cargo install. Well it's actually possible to cargo install via git:

```
cargo install --git https://github.com/mpizenberg/elm-test-rs --tag v3.0
```

So I'm closing this issue now. If that wasn't the purpose, please reopen and explain further.
