### ISSUE TITLE
Add elm-tooling support

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-test-rs#32]
https://github.com/lydell/elm-tooling.json

**Comment by mpizenberg** [comment]
Once a way to describe [tests entry points is specified](https://github.com/lydell/elm-tooling.json/issues/17), we just have to parse the `elm-tooling.json` to load that information when no file is passed as command line argument.

**Comment by Razzeee** [comment]
Done by https://github.com/elm-tooling/elm-tooling-cli/commit/65e9e057e033e528331609cc2e223be71dcbc8f8

**Comment by lydell** [comment]
@Razzeee No, this is actually about implementing what comes out of https://github.com/lydell/elm-tooling.json/issues/17 (if anything), I believe

**Comment by mpizenberg** [comment]
Indeed, that was more related to what comes out of the discussion in the issue linked by @lydell related to entry points for tests.

**Comment by mpizenberg** [comment]
But this issue title is a bit confusing and the intent is actually depending on hypothetical stuff in another repo (the elm-tooling spec) so I'll just go ahead and close this. If/When we have a concrete elm-tooling.json spec for this I'll reopen a new issue.
