### ISSUE TITLE
Split dependencies into direct and indirect to prevent collisions of Base64 packages

### ISSUE THREAD

**Issue by Janiczek** [mpizenberg/elm-test-rs#50]
Base64 packages have conflicting module names; application that only uses one of them but has the other one in indirect deps can work and be tested with `elm-test` just fine, but `elm-test-rs` fails because it doesn't distinguish between direct and indirect deps and they end up in the same "module name space".

----

Creating this issue as a result of this Slack thread:
https://elmlang.slack.com/archives/C0CLGCMMF/p1611225607000900

Here's the thread as a screenshot (we all know how fast the Slack history disappears :) ):
![thread](https://user-images.githubusercontent.com/149425/105341437-61b4b700-5bdf-11eb-9ae8-f5545d0c7c0d.png)

----

Here's the linked code:
https://github.com/mpizenberg/elm-test-rs/blob/22a5a8dd0d6120a33a470fca5a9933af43ddb086/src/deps.rs#L203

**Comment by mpizenberg** [comment]
Thanks for the report! I'll fix it in the weekend I think. Also noted it as good first issue for potential interested contributor since I believe it's a rather easy fix.

**Comment by mpizenberg** [comment]
[Version 0.6](https://github.com/mpizenberg/elm-test-rs/releases/tag/v0.6) should fix your issue. Let me know if that's not the case!

**Comment by mpizenberg** [comment]
Actually 0.6 introduced a bug while splitting indirect deps (elm/json potentially missing in direct deps). Fixed in [0.6.1](https://github.com/mpizenberg/elm-test-rs/releases/tag/v0.6.1).

**Comment by mpizenberg** [comment]
I'll consider it fixed, let me know if you're still facing issues.
