### ISSUE TITLE
race condition in watch mode

### ISSUE THREAD

**Issue by harrysarson** [mpizenberg/elm-test-rs#76]
Hi, 

The seems to be a delay between starting the elm-test-rs process and the start of watch mode. This means that there is a time window during which I can change a file so that the changes are _not_ included in the initial run _and_ the changes do _not_ cause the tests to be re-run.

I can reproduce consistently with:

```shell
node-test-runner/tests/fixtures on  master [$!⇣] via 🌳 v0.19.1 took 2s 
❯ elm-test-rs --report json --watch tests/Passing/One.elm & sleep 0.1; echo "fail" >> tests/Passing/One.elm                                               [18:20:52]
[1] 26669

elm-test-rs 1.0.0-beta for elm 0.19.1
--------------------------------

✓ Compilation of tests modules succeeded

node-test-runner/tests/fixtures on  master [$!⇣] via 🌳 v0.19.1 
✦ ❯ {"event":"runStart","testCount":"1","initialSeed":"4048490339","fuzzRuns":"100","globs":["tests/Passing/One.elm"],"paths":["/home/harry/repo/node-test-runner/tests/fixtures/tests/Passing/One.elm"]}
{"event":"testsCompleted","status":"pass","labels":["this should pass"],"failures":[],"duration":"1.412781000137329"}
{"event":"runComplete","passed":"1","failed":"0","duration":"1.412781000137329","autoFail":null}
Running duration (since Node.js start): 104 ms

```

If the sleep is much less than a 10th of a second the initial run fails (due to syntax error) if it is much more than a tenth of a second the tests are re-run (and fail due to a syntax error).

**Comment by mpizenberg** [comment]
Currently, the watch only start at the end of running the tests the first time, so anything happening between the moment that the `Runner.elm` has been generated and the end of the first tests run will be silently ignored. That same behavior is repeated in the loop, as can be seen here: https://github.com/mpizenberg/elm-test-rs/blob/2d9b029022a680f62b23d266866d15ebbd628bcd/src/run.rs#L68

I haven't invested a lot of time in that watch mode, its mechanics are the following, in pseudo code:
```
directories_to_watch = run_tests(arguments)
on_watch_change(directories_to_watch) {
    directories_to_watch = run_tests(arguments)
}
```
There are definitely better ways to handle that. I'd love if someone has a better way that's also rather simple code-wise!

**Comment by mpizenberg** [comment]
Thanks for reporting that race condition!

**Comment by lydell** [comment]
In node-test-runner we start watching _before_ compiling and running tests.

Once here: https://github.com/rtfeldman/node-test-runner/blob/0fa6bc16f9a635303b95b9e22c40df5921e5f80a/lib/RunTests.js#L301-L305

And every loop here: https://github.com/rtfeldman/node-test-runner/blob/0fa6bc16f9a635303b95b9e22c40df5921e5f80a/lib/RunTests.js#L190-L195
