### ISSUE TITLE
Native support for Apple M1 + CI builds

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-test-rs#78]
It would be nice to know if elm-test-rs builds correctly for Apple M1. It would also be nice to know if at can be built from an x86 machine with cross compilation, such that we can do it on CI with GitHub actions. This is a tracking issue for that.

If an Apple user wants to try that, feedback is welcome!

**Comment by koctya** [comment]
I got a M1 MacBook Pro in new job, I can try it sometime this week, and give feedback.

**Comment by koctya** [comment]
compiles Ok, runs help, I'll try using it this week.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/621976/119239782-52a42e00-bb19-11eb-9943-bfe7e587b55b.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/621976/119239795-618ae080-bb19-11eb-9d2f-e47c35537b51.png">

**Comment by mpizenberg** [comment]
That's amazing news thanks @koctya ! Now we have to add a cross-compiled M1 target to the github CI to see if that would also work.

**Comment by mpizenberg** [comment]
Hi @koctya , I think I've managed to add Apple M1 builds to the CI (doing this here in #91). If you have the time, I'd love if you could try the M1 build which is in the "Artifacts" of this CI build: https://github.com/mpizenberg/elm-test-rs/pull/91/checks?check_run_id=3185963058. The M1 is the one called "elm-test-rs_aarch64-apple-darwin"

**Comment by mpizenberg** [comment]
Done in #91
