### ISSUE TITLE
Add option to enable/disable automatic module description

### ISSUE THREAD

**Issue by grrinchas** [mpizenberg/elm-test-rs#88]
I understand the reasoning not appending module name, but having exposed functions inside the test module is very useful for writing `elm-review` rules. 

So given following module

```elm
Model exposing (a, b, c)
```

And corresponding test module, 

```elm
TestModel exposing (aTest, bTest)
```
Is very clear that functions `a` and `b` have a corresponding test, while `c` does not. 

And making the same check with the following code, becomes harder.

```elm
TestModule exposing (tests)

tests = describe "TestModule" [ aTest, bTest, cTest ]
```

Would be nice to have an option which auto append module name to the description.

**Comment by mpizenberg** [comment]
Hi @grrinchas I'm not so sure to follow what you mean. Also I haven't written elm review rules myself so a concrete example of something not working for you would be nice.

By the way, I'm not following why you'd want to have `cTest` inside that describe. Why would you not have
```elm
TestModule exposing (tests)

tests = describe "TestModule" [ aTest, bTest ]

aTest = ...
bTest = ...
cTest = ...
```

**Comment by grrinchas** [comment]
Hi @mpizenberg. Sorry, had to be more precise.

So basically, I have `elm-review` rule which checks if a function in a module have a corresponding test function inside test module. 

And the way it is implemented is very simple. it just compares functions which are exposed in the original module with the ones which are exposed in the test module. 

Using the following will break that rule. Cause the only function which is exposed in this case is `tests`.

```elm
TestModule exposing (tests)

tests = describe "TestModule" [ aTest, bTest ]
```

Of course I can change the `elm-review` rule, by looking for function `suite` or `tests` then checking what functions it has. Or just looping through all the functions in the module itself and comparing. 

The point is that knowing which functions are exposed inside the module is useful information. And this pattern makes that information less accessible in the AST.

**Comment by mpizenberg** [comment]
And I suppose you have functions of name `aTest` in multiple tests modules? Otherwise no need for that `describe`.

**Comment by jfmengels** [comment]
Hi @grrinchas :wave: 

I imagine that for the purpose of this rule, you can instead look for whether there is a top-level `<fnName>Test : Test` declaration if you rely on `NoUnused.Variables` rule: If the function is not exposed, then it will be reported/removed, and the rule you wish to write right now will detect that it's missing.

I'm a bit worried that your rule will create (too heavy) constraints on how your tests are structured. Such as if `aTest` is really big, then you might want to create a dedicated file just for it, which this rule would prevent. Also, I don't know how realistically feasible it is to have a test for every function, without testing implementation details (unless you're only testing exposed functions for a package). Anyway, this is not the best place to discuss here, so please join #elm-review on the Elm Slack or create a thread in https://github.com/jfmengels/elm-review/discussions/categories/rule-ideas. I'm very curious as to whether this rule will give good results!

**Comment by grrinchas** [comment]
`describe` is used to group tests together for one function, and the name of it usually is the function name itself. For example. If if you have function `toString` in `ModelA` then you would have a test inside `ModelATest`

```elm 
toStringTest : Test.Test
toStringTest =
    Test.describe "toString"
        [ Test.test "if Nothing returns empty string"
        , Test.test "if Just returns `value`"
        ]
```
But of course `toString` function is very common, so you get lots of collisions of `Test.describe`

One solution would be to have something like `Test.describe "ModelA.toString` but then you will have to change the function every time model name changes.

**Comment by mpizenberg** [comment]
@grrinchas I see. I find @jfmengels idea of combining `NoUnused.Variables` with a rule of yours checking existence of a top-level `<fnName>Test : Test` to be a more flexible solution. Let me know if you try it and it solves your issue.

**Comment by mpizenberg** [comment]
I suppose you managed to solve your issue?

**Comment by grrinchas** [comment]
Yes I did. 

Provided solution did work. The issue can be closed. Thanks.
