### ISSUE TITLE
Allow running Node with --inspect-brk or other custom args to help debugging crashes

### ISSUE THREAD

**Issue by Janiczek** [mpizenberg/elm-test-rs#90]
Currently when running the supervisor it is not possible to plug in our own arguments to the node binary:

https://github.com/mpizenberg/elm-test-rs/blob/d21e9623ee9a6b3f9ba516cd6610a627e321d170/src/run.rs#L187

It would be useful to me to be allowed to give it `--inspect-brk` or something similar, to allow debugging problems like this one:

<img width="705" alt="Screenshot 2021-07-10 at 1 06 58" src="https://user-images.githubusercontent.com/149425/125143458-21a8a880-e11b-11eb-80f4-7ada6f0cb528.png">

With `--inspect-brk` I could connect to the Node process with Chrome devtools and use its stepping debugger to see what happens inside the test.

**Comment by Janiczek** [comment]
Actually, I've tried this real quick with:
```diff
diff --git a/src/main.rs b/src/main.rs
index ee7d24a..2306023 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -88,6 +88,11 @@ fn main() -> anyhow::Result<()> {
             .possible_value("junit")
             .possible_value("exercism")
             .help("Print results to stdout in the given format"),
+        Arg::with_name("node-args")
+            .long("node-args")
+            .takes_value(true)
+            .value_name("string")
+            .help("Pass arguments to the Node process that will run the tests"),
     ];
     let matches = App::new("elm-test-rs")
         .version(std::env!("CARGO_PKG_VERSION"))
@@ -236,6 +241,7 @@ fn get_run_options(arg_matches: &clap::ArgMatches) -> anyhow::Result<run::Option
         workers,
         filter: arg_matches.value_of("filter").map(|s| s.to_string()),
         reporter: report.to_string(),
+        node_args: arg_matches.value_of("node-args").map(|s| s.to_string()),
     })
 }
 
diff --git a/src/run.rs b/src/run.rs
index 72943ff..3d995e3 100644
--- a/src/run.rs
+++ b/src/run.rs
@@ -20,6 +20,7 @@ pub struct Options {
     pub workers: u32,
     pub filter: Option<String>,
     pub reporter: String,
+    pub node_args: Option<String>,
 }
 
 /// Wrapper for the main_helper function with "watch" functionality.
@@ -186,6 +187,7 @@ fn main_helper(
     log::info!("Starting the supervisor ...");
     let mut supervisor = Command::new("node")
         .args(experimental_arg)
+        .args(&run_options.node_args)
         .arg(node_supervisor_js_file)
         .current_dir(tests_root)
         .stdin(Stdio::piped())
```
which does what I want if ran as `elm-test-rs --node-args="--inspect-brk"` :tada:
but I still haven't figured out how to get the debugger inside the `node_runner.js` worker. So I'm not sure the feature I requested above would help me. Still tinkering though!

**Comment by mpizenberg** [comment]
Interesting! I'll have a look into it when I come back from holiday next week

**Comment by Janiczek** [comment]
So far I've found out that Chrome DevTools don't support Node Workers yet. ❌ 

There is something called `ndb` with which you can run `ndb node ...` instead of `node ...` and that tool supposedly _has_ support for Node Workers. ✅ 

`vscode-js-debug` also supposedly has support for debugging them. ✅ 

I'll try to evaluate these two options before giving up on this 🙃

**Comment by Janiczek** [comment]
Houston, we're inside! :smile:

<img width="1552" alt="Screenshot 2021-07-10 at 1 47 49" src="https://user-images.githubusercontent.com/149425/125145270-ed37eb00-e120-11eb-96df-c4097b575073.png">

In the end my whole diff was:
```diff
diff --git a/src/run.rs b/src/run.rs
index 72943ff..315c613 100644
--- a/src/run.rs
+++ b/src/run.rs
@@ -184,7 +184,7 @@ fn main_helper(

     // Start the tests supervisor
     log::info!("Starting the supervisor ...");
-    let mut supervisor = Command::new("node")
+    let mut supervisor = Command::new("ndb")
         .args(experimental_arg)
         .arg(node_supervisor_js_file)
         .current_dir(tests_root)
```
I was able to install `ndb` simply with `yarn global add ndb`.
Then when I ran `elm-test-rs`, it opened up a special version of Chromium Dev Tools that can debug worker threads too.
There I opened `Runner.elm.js` inside the devtools and made a breakpoint inside `_Test_runThunk`:

<img width="469" alt="Screenshot 2021-07-10 at 1 51 09" src="https://user-images.githubusercontent.com/149425/125145411-561f6300-e121-11eb-82d6-794b115fe74c.png">

And that allowed me to look at the stack message, which had some hints as to what parts of my Elm code are buggy.

# Conclusion

My conclusion is very different from what I thought it would be.

I think it would be benefitial if `_Test_runThunk` also reported the stack alongside the message itself, and for `Test.Runner.run` to show that value in case of the `"This test failed because it threw an exception:"` scenario.

As for whether elm-test-rs should change anything about itself - probably not :) Thanks for the tool!! It was very easy to hack on it BTW. :+1:

**Comment by mpizenberg** [comment]
Glad you found a way!
