### ISSUE TITLE
--watch to clear the terminal or print a delimiter when starting a new run

### ISSUE THREAD

**Issue by Janiczek** [mpizenberg/elm-test-rs#95]
This is a difference between `elm-test-rs` and tools like `elm-review` or webpack dev server: `elm-test-rs` doesn't give any indication that a new run has begun (after the user saved etc.), and the new compiler errors get concatenated to the old errors above them. This sometimes causes a confusing output, as you might want to fix a second+ error from the bottom, and it might belong to the old run and not be relevant anymore.

https://user-images.githubusercontent.com/149425/133662349-38c038cc-21e3-4891-a780-e0a4150d70ca.mp4

In my view there are two good options:
* clear the terminal history like `elm-review` does
* or write something like "Watched files changed, compiling/testing again" in between the runs (sorry for the crappy copy)

That would both signal to the user which runs to look at.

**Comment by mpizenberg** [comment]
Agreed! Do you have any preference or thought on the ups and downs of each approach?

**Comment by mpizenberg** [comment]
Delimiter approach was done in #96
